# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-13 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
        ),
    ]
