# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-03 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Country',
            new_name='country',
        ),
    ]
